from app.schemas.feature import FeaturePublic

FEATURE_CATALOG: list[FeaturePublic] = [
    FeaturePublic(
        slug="misinformation-detector",
        name="Misinformation Detector",
        status="available",
        category="trust-and-safety",
        description="Classifies text content as likely real or fake using the current ML model.",
    ),
    FeaturePublic(
        slug="sentiment-analysis",
        name="Sentiment Analysis",
        status="planned",
        category="text-intelligence",
        description="Will analyze tone and polarity for user-submitted content.",
    ),
    FeaturePublic(
        slug="ai-content-detection",
        name="AI Content Detection",
        status="planned",
        category="trust-and-safety",
        description="Will estimate whether submitted text was likely generated by AI.",
    ),
    FeaturePublic(
        slug="cv-optimizer",
        name="CV Optimizer",
        status="planned",
        category="career-tools",
        description="Will help improve CV clarity, impact, and job targeting.",
    ),
]


def get_feature_catalog() -> list[FeaturePublic]:
    return FEATURE_CATALOG
